*this is where i'll work on the data*

# 1) Clean & Tidy data 

This will take up the largest chunk of our time!

## Load Data & Packages

First let's load in and look at our raw data:

In [9]:
# import packages
import pandas as pd # for data manipulation
import numpy as np # for operations and uniforming data
import matplotlib.pyplot as plt # for data viz
import seaborn as sns #for data viz

# load raw data (this is a version of survey when there were 30 responses, but the column names are the same as the version with 50 responses, so we can use this for testing our code before we run it on the full dataset)

csv_file = 'C:\\Users\\aranz\\OneDrive\\music_and_motivation\\music-motivation-survey-repo\\data\\raw\\survey_30_responses_(starter).csv'
survey_df = pd.read_csv(csv_file)

# view data
survey_df.head()

,Timestamp,Score,First and Last Name,Email,Do you believe yourself to be Introverted or Extroverted?,What is your gender identity?,Which category best describes you? (select all that apply),What is your preferred music genre? (on a daily basis),"On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)",How old are you?,...,"When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?",Why do you go to parties?,What is/are your ethnicity/ies?,What is/are your nationality/ ies?,"On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)","On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?","Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)","Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*","Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)",Column 12
0,2/25/2026 12:10:43,NaN,NaN,NaN,NaN,Male,NaN,"Electronic, Pop",3,23,...,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i...",NaN
1,2/25/2026 12:19:46,NaN,NaN,NaN,NaN,Female,NaN,Hip Hop & R&B,2,20,...,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more",NaN
2,2/25/2026 12:21:41,NaN,NaN,NaN,NaN,Female,NaN,"Hip Hop & R&B, Pop",4,21,...,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ...",NaN
3,2/25/2026 12:32:51,NaN,NaN,NaN,NaN,female,NaN,"Hip Hop & R&B, Pop",3,19,...,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...,NaN
4,2/25/2026 12:38:44,NaN,NaN,NaN,NaN,Female,NaN,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,...,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN,NaN

There's a bunch of columns that we actually don't need because no data ended up being needed to be recorded from them so I'll get rid of those:

In [10]:
# see column names
survey_df.columns

Index(['Timestamp', 'Score', 'First and Last Name ', 'Email',
       'Do you believe yourself to be Introverted or Extroverted?',
       'What is your gender identity? ',
       'Which category best describes you? (select all that apply) ',
       'What is your preferred music genre? (on a daily basis) ',
       'On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)',
       'How old are you? ', 'What is your college major? ', 'Email Address',
       'On a daily basis, what is the language of music you listen to? ',
       'What is your preferred music genre to listen to at parties? ',
       'What are your top 5 Artists for going out? ',
       'What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*',
       'What do you like about the parties you have gone to so far? (music, environment, loudness, etc. ) ',
       'What don't you like about parties? (music, environment, loudness, etc. ) ',
       'On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)',
       'How many times have you gone to a gathering in the last 2 months?',
       'What emotions do you feel when listening to these top 5 songs?',
       'On a scale of 1-5, how likely are you to come up to a stranger at a party sober? \n(1 = very unlikely, 5 = very likely)',
       'On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)',
       'When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?',
       'Why do you go to parties?', 'What is/are your ethnicity/ies?',
       'What is/are your nationality/ ies?',
       'On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)',
       'On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?',
       'Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)',
       'Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*',
       'Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)',
       'Column 12'],
      dtype='object')

In [11]:
# removing columns that are not needed for analysis which are the ones with all missing values
survey_df = survey_df.dropna(axis=1, how='all')

survey_df.head()

,Timestamp,What is your gender identity?,What is your preferred music genre? (on a daily basis),"On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)",How old are you?,What is your preferred music genre to listen to at parties?,"What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*","What do you like about the parties you have gone to so far? (music, environment, loudness, etc. )","What don't you like about parties? (music, environment, loudness, etc. )","On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)",...,"On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)","When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?",Why do you go to parties?,What is/are your ethnicity/ies?,What is/are your nationality/ ies?,"On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)","On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?","Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)","Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*","Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)"
0,2/25/2026 12:10:43,Male,"Electronic, Pop",3,23,"Hip Hop & R&B, Pop","Rhianna - Where Have You Been, Bad Bunny - EoO...","I liked the music they've had, and the convers...",I don't like when others excessively use subst...,4,...,5,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i..."
1,2/25/2026 12:19:46,Female,Hip Hop & R&B,2,20,"Hip Hop & R&B, Electronic, Pop","Melancholy Hill, any Rocco song, Love Me Not, ...","The people there, the loudness","The environment, how parties always happe so late",2,...,5,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more"
2,2/25/2026 12:21:41,Female,"Hip Hop & R&B, Pop",4,21,"Hip Hop & R&B, Electronic, Pop",any spanish reggaeton song or early 2000s pop ...,"music, dancing, and environment","If the music is bad, awkward people or not eno...",5,...,3,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ..."
3,2/25/2026 12:32:51,female,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Electronic, Pop","time to pretend mgmt, spin about you drake, lo...","music, chalant people, welcoming crowd",rude nonchalant people,2,...,1,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...
4,2/25/2026 12:38:44,Female,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,"Hip Hop & R&B, Pop","DtMF by bad bunny, luther by kendrick and sza,...",I like the music and just seeing the general h...,I don't typically like the drinking environmen...,1,...,5,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN

## Renaming Columns

The column names are pretty long so I'll reformat them to be easier to call on and stuff:

In [12]:
# getting column names again after dropping columns and also seeing how many questions there are in the survey

i=0
for col in survey_df.columns:
    print(f"#{i}: {col}")
    i += 1

survey_df.columns.to_list()

#0: Timestamp
#1: What is your gender identity?
#2: What is your preferred music genre? (on a daily basis)
#3: On a scale of 1-5, how introverted are you?
(1 = introverted, 5 = extroverted)
#4: How old are you?
#5: What is your preferred music genre to listen to at parties?
#6: What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)?

*Please specify song title and artist(s)!*
#7: What do you like about the parties you have gone to so far? (music, environment, loudness, etc. )
#8: What don't you like about parties? (music, environment, loudness, etc. )
#9: On a scale of 1-5, how likely are you to pregame before a party/gathering?
(1 = very unlikely, 5 = very likely)
#10: How many times have you gone to a gathering in the last 2 months?
#11: What emotions do you feel when listening to these top 5 songs?
#12: On a scale of 1-5, how likely are you to come up to a stranger at a party sober?
(1 = very unlikely, 5 = very likely)
#13: On a scale of 1-5, how likely are you to sing along to a song at a party sober?
(1 = very unlikely, 5 = very likely)
#14: When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?
#15: Why do you go to parties?
#16: What is/are your ethnicity/ies?
#17: What is/are your nationality/ ies?
#18: On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?
(1 = very unlikely, 5 = very likely)
#19: On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?
#20: Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)
#21: Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!

*Please specify song title and artist(s)!*
#22: Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)

['Timestamp',
 'What is your gender identity? ',
 'What is your preferred music genre? (on a daily basis) ',
 'On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)',
 'How old are you? ',
 'What is your preferred music genre to listen to at parties? ',
 'What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*',
 'What do you like about the parties you have gone to so far? (music, environment, loudness, etc. ) ',
 "What don't you like about parties? (music, environment, loudness, etc. ) ",
 'On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)',
 'How many times have you gone to a gathering in the last 2 months?',
 'What emotions do you feel when listening to these top 5 songs?',
 'On a scale of 1-5, how likely are you to come up to a stranger at a party sober? \n(1 = very unlikely, 5 = very likely)',
 'On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)',
 'When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?',
 'Why do you go to parties?',
 'What is/are your ethnicity/ies?',
 'What is/are your nationality/ ies?',
 "On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)",
 "On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?",
 'Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)',
 'Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*',
 'Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)']

In [13]:
# change column names to be more descriptive and easier to work with
survey_df = survey_df.rename(columns={

    # Demographics
    'What is your gender identity? ': 'gender',
    'How old are you? ': 'age',
    'What is/are your ethnicity/ies?': 'ethnicity',
    'What is/are your nationality/ ies?': 'nationality',
    'On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)': 'introversion_score',

    # Music Preferences
    'What is your preferred music genre? (on a daily basis) ': 'preferred_genre_daily', 
    'What is your preferred music genre to listen to at parties? ': 'preferred_genre_parties',
    'What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*': 'top_5_songs_before_going_out',
    'What emotions do you feel when listening to these top 5 songs?': 'emotions_top_5_songs',
    'Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*': 'top_5_songs_when_hosting_party',    
    'When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?': 'party_playlist_intent',

    # Party Experiences
    'Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)': 'party_experience_sober',
    'On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)': 'pregame_likelihood_score',
    'How many times have you gone to a gathering in the last 2 months?': 'times_in_last_2_months',
    'On a scale of 1-5, how likely are you to come up to a stranger at a party sober? \n(1 = very unlikely, 5 = very likely)': 'likelihood_approach_stranger_score',
    'On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)': 'likelihood_sing_along_score',
    "On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)": 'likelihood_conversation_no_music_score',
    "On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?": 'likelihood_conversation_loud_music_score',
    'Why do you go to parties?': 'reason_for_going_to_parties',
    'What do you like about the parties you have gone to so far? (music, environment, loudness, etc. ) ': 'party_likes',
    "What don't you like about parties? (music, environment, loudness, etc. ) ": 'parties_dislikes',

    # Interview Participation
    'Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)': 'interview_participation_email',
})

#let's look at the dataframe again after renaming the columns:
survey_df.head()

,Timestamp,gender,preferred_genre_daily,introversion_score,age,preferred_genre_parties,top_5_songs_before_going_out,party_likes,parties_dislikes,pregame_likelihood_score,...,likelihood_sing_along_score,party_playlist_intent,reason_for_going_to_parties,ethnicity,nationality,likelihood_conversation_no_music_score,likelihood_conversation_loud_music_score,interview_participation_email,top_5_songs_when_hosting_party,party_experience_sober
0,2/25/2026 12:10:43,Male,"Electronic, Pop",3,23,"Hip Hop & R&B, Pop","Rhianna - Where Have You Been, Bad Bunny - EoO...","I liked the music they've had, and the convers...",I don't like when others excessively use subst...,4,...,5,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i..."
1,2/25/2026 12:19:46,Female,Hip Hop & R&B,2,20,"Hip Hop & R&B, Electronic, Pop","Melancholy Hill, any Rocco song, Love Me Not, ...","The people there, the loudness","The environment, how parties always happe so late",2,...,5,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more"
2,2/25/2026 12:21:41,Female,"Hip Hop & R&B, Pop",4,21,"Hip Hop & R&B, Electronic, Pop",any spanish reggaeton song or early 2000s pop ...,"music, dancing, and environment","If the music is bad, awkward people or not eno...",5,...,3,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ..."
3,2/25/2026 12:32:51,female,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Electronic, Pop","time to pretend mgmt, spin about you drake, lo...","music, chalant people, welcoming crowd",rude nonchalant people,2,...,1,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...
4,2/25/2026 12:38:44,Female,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,"Hip Hop & R&B, Pop","DtMF by bad bunny, luther by kendrick and sza,...",I like the music and just seeing the general h...,I don't typically like the drinking environmen...,1,...,5,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN

In [14]:
# and let's look at the column names again to make sure they are correct:
survey_df.columns.to_list(), len(survey_df.columns)

(['Timestamp',
  'gender',
  'preferred_genre_daily',
  'introversion_score',
  'age',
  'preferred_genre_parties',
  'top_5_songs_before_going_out',
  'party_likes',
  'parties_dislikes',
  'pregame_likelihood_score',
  'times_in_last_2_months',
  'emotions_top_5_songs',
  'likelihood_approach_stranger_score',
  'likelihood_sing_along_score',
  'party_playlist_intent',
  'reason_for_going_to_parties',
  'ethnicity',
  'nationality',
  'likelihood_conversation_no_music_score',
  'likelihood_conversation_loud_music_score',
  'interview_participation_email',
  'top_5_songs_when_hosting_party',
  'party_experience_sober'],
 23)

## Cleaning Survey Data

Now we wanna make sure our data is pretty clean, meaning there's no substantial amounts of missing values and see if responses are what they should be. To be honest, there shouldn't be many missing values since most questions are required (other than "Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.) and something else I think?)

In [15]:
# checking missing values in each column
survey_df.isnull().sum()

Timestamp                                   0
gender                                      0
preferred_genre_daily                       0
introversion_score                          0
age                                         0
preferred_genre_parties                     0
top_5_songs_before_going_out                0
party_likes                                 0
parties_dislikes                            0
pregame_likelihood_score                    0
times_in_last_2_months                      0
emotions_top_5_songs                        0
likelihood_approach_stranger_score          0
likelihood_sing_along_score                 0
party_playlist_intent                       0
reason_for_going_to_parties                 0
ethnicity                                   0
nationality                                 0
likelihood_conversation_no_music_score      0
likelihood_conversation_loud_music_score    0
interview_participation_email               5
top_5_songs_when_hosting_party              1
party_experience_sober                      4
dtype: int64

In [16]:
# only 3 columns have missing values, let's look at them:
survey_df[['party_experience_sober', 'top_5_songs_when_hosting_party', 'interview_participation_email']]

,party_experience_sober,top_5_songs_when_hosting_party,interview_participation_email
0,"Yes I have. While I feel more shy sometimes, i...","Bad Bunny - Baile Inolvidable, Karol G - Si An...",admontan@ucsd.edu
1,"Yes, I laughed more","Any Daniel ceasar song, Melancholy Hill, Every...",No
2,"Yes, I tried drinking but I ended up throwing ...",never hosted before but would put Spanish regg...,N/a
3,yes it was chill everybody was already in a ha...,"lady killers, 3 strikes, girlfriend heavy weig...",no
4,NaN,"I like all the stars by kendrick and sza, titi...",No thank you
5,"yes; if the music is good, i tend to have a go...","talk talk - charli xcx, stateside + bladee - p...",suree; mjsok@ucsd.edu
6,i enjoyed witnessing everyone that was not sober,"latch- disclosure, doses&mimosas- cherub, savi...",no sorry😓😓
7,NaN,I have no idea,I don't have experience
8,"Yes. Honestly, I prefer to be sober at parties...","All I Ever Asked by Rachel Chinouriri, Love is...",brittneydnguyen@gmail.com
9,"I have only been sober at parties, and it can ...","deep in it by berlioz, breezy (inst.) by rolle...",santiago.valdivia1111@gmail.com
10,I was more calm and not as willing to talk to ...,"Tiene espinas el rosal, love generation, inolv...",No
11,No,"Gasolina, no hands, party rock anthem, clarity...",No
12,nope,i don’t host,NaN
13,"yes, it can be just as fun with the right peop...","trap queen-fetty wap, roses- chainsmokers, cla...",yur @esk01012006@gmail.com
14,NaN,NaN,NaN
15,No,"1) Clarity by Zedd, 2) Smokin Out The Window b...",Yes: t9doan@ucsd.edu
16,Yes it out but I was a little bored when I we...,"F.n.f -gorilla, gas pedal - sage the Gemini , ...",J4blanco@ucsd.edu
17,NaN,"We are the people by empire of the sun, My lov...",No thank you
18,"Yes, well, it’s exciting because I really enj...","1.- Don’t stop the party, 2.- perdóname -facto...","Yes, salmup26@gmail.com or i24221220.02@puebla..."
19,I don’t really like to drink and I would say I...,"Any drake, A$AP, Spanish music,Rihanna",No thank u!
20,no,"throw sum mo- swae lee, we found love- rihanna...",yes ivanatram33@gmail.com
21,I liked that I was able to have a good time wi...,"El Liston De Tu Pelo(Los Angeles Azules), 20 R...",NaN
22,no,"I don't host parties, but definitely heavy bea...",no
23,"Yes, I liked how upbeat the music was and how ...","So Easy by Olivia Dean, NEW DROP by Don Tolive...",NaN
24,It was kinda boring when I was sober because m...,"Gasolina (daddy yankee), Party in the USA(Mile...",NaN
25,"Yes, it was honestly just as fun. I went with ...","Clarity zedd, meet me halfway black eyed peas,...",I’m ok
26,"yes, but going to a party sober makes the expe...","Club Classics (charli xcx), Stay the night (Ze...",no thank you!
27,"Yes, I like being more aware but when I’m not ...","Clarity - Zedd, Inténtalo- 3BallMTY, Porque El...",epizarroalfaro@ucsd.esu
28,"yes, it was a bit scary because i am socially ...","fw me (dirty) - knock2 & rhea raj, i got a que...",natnatnatalie18@gmail.com
29,Yes. It was nice getting to know people and ha...,"-MyWay (Fetty Wap), Maneater (Nelly Furtado), ...",YES (khyun@ucsd.edu)

In [17]:
# weird, row 14 yas NaN for the 3 rows, let's look at the original dataframe to see if there is something wrong with the data in that row:
survey_df.iloc[14]

Timestamp                                                                  2/25/2026 15:23:33
gender                                                                                 Female
preferred_genre_daily                                                      Hip Hop & R&B, Pop
introversion_score                                                                          3
age                                                                                        20
preferred_genre_parties                                        Hip Hop & R&B, Electronic, Pop
top_5_songs_before_going_out                        No Hands, OMG, Blackout, Blame It, Issues
party_likes                                      Good music, good drinks, good vibes & people
parties_dislikes                                                 Vibes that are not welcoming
pregame_likelihood_score                                                                    4
times_in_last_2_months                                                                      2
emotions_top_5_songs                                                Very hyped up and excited
likelihood_approach_stranger_score                                                          2
likelihood_sing_along_score                                                                 2
party_playlist_intent                                         Depends on the vibe of the look
reason_for_going_to_parties                 For fun and to socialize with new people/curre...
ethnicity                                                                         Vietnamese
nationality                                                                   Asian American
likelihood_conversation_no_music_score                                                      2
likelihood_conversation_loud_music_score                                                    2
interview_participation_email                                                             NaN
top_5_songs_when_hosting_party                                                            NaN
party_experience_sober                                                                    NaN
Name: 14, dtype: object

honeslty idk why or how those values are missing for that individual, especially since `top_5_songs_when_hosting_party` is a required response field but maybe the survey had changed somehow since she took it? Anyway I think the mising values we have aren't a big deal so I'll go ahead and keep it as is. now we wanna tidy up the data!

### Cleaning responses & Uniforming Data

#### Gender Clean-up
Ok so clearly people don't know what nationality vs ethnicity is so we're gonna have to clean that up a bit or change it to race I honestly don't know lol.

Also for the `gender` data, people also clearly don't know the difference b/w sex and gender lol. Most ppl wrote 'female' or 'male' so maybe we can clean it up by just standardizing the responses to sex? but there were some entries like 'gender fluid (fem) and for some reason 'Straight' bruhhh'

In [18]:
# first will make gender column uniform by changing all values to lowercase and removing extra spaces
survey_df['gender'] = survey_df['gender'].str.lower().str.strip()

# now let's see what unique values there are in the gender column to see if there are any other variations of the same gender:
survey_df['gender'].unique()

array(['male', 'female', 'genderfluid (fem)', 'heterosexual female',
       'she/her female', 'men', 'she/her'], dtype=object)

**1) 'male' / 'man'**

Ok so for males, there is 'male' & 'men' still. We could either standardize to make anything listed as that as either 'male' or 'men' --> the correct response for gender would be 'men'

**2) 'female'/ 'woman'**

For 'female' there's a lot of unqiue entries essentially saying the same thing, including 'heterosexual female', 'she/her female', and 'she/her'

**3) 'non-binary'**

There's only one response that could fit this called 'genderfluid (fem)'

*So now let's just write some code to standardize the data to gender:*

In [19]:
# we're going to standardize the gender column by replacing all variations of the same categories ('woman', 'man', 'genderfluid') to the same value, and then we will reassign them to the gender column:
for gender in survey_df['gender']:
    if 'woman' in gender or 'she/her' in gender or 'female' in gender:
        survey_df['gender'] = survey_df['gender'].replace(gender, 'woman')
    elif 'man' in gender or 'men' in gender or 'male' in gender or 'he/him' in gender:
        survey_df['gender'] = survey_df['gender'].replace(gender, 'man')
    elif 'genderfluid' in gender or 'non-binary' in gender or 'they/them' in gender:
        survey_df['gender'] = survey_df['gender'].replace(gender, 'non-binary')

# let's check the unique values again to make sure they are standardized:
survey_df

,Timestamp,gender,preferred_genre_daily,introversion_score,age,preferred_genre_parties,top_5_songs_before_going_out,party_likes,parties_dislikes,pregame_likelihood_score,...,likelihood_sing_along_score,party_playlist_intent,reason_for_going_to_parties,ethnicity,nationality,likelihood_conversation_no_music_score,likelihood_conversation_loud_music_score,interview_participation_email,top_5_songs_when_hosting_party,party_experience_sober
0,2/25/2026 12:10:43,man,"Electronic, Pop",3,23,"Hip Hop & R&B, Pop","Rhianna - Where Have You Been, Bad Bunny - EoO...","I liked the music they've had, and the convers...",I don't like when others excessively use subst...,4,...,5,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i..."
1,2/25/2026 12:19:46,woman,Hip Hop & R&B,2,20,"Hip Hop & R&B, Electronic, Pop","Melancholy Hill, any Rocco song, Love Me Not, ...","The people there, the loudness","The environment, how parties always happe so late",2,...,5,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more"
2,2/25/2026 12:21:41,woman,"Hip Hop & R&B, Pop",4,21,"Hip Hop & R&B, Electronic, Pop",any spanish reggaeton song or early 2000s pop ...,"music, dancing, and environment","If the music is bad, awkward people or not eno...",5,...,3,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ..."
3,2/25/2026 12:32:51,woman,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Electronic, Pop","time to pretend mgmt, spin about you drake, lo...","music, chalant people, welcoming crowd",rude nonchalant people,2,...,1,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...
4,2/25/2026 12:38:44,woman,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,"Hip Hop & R&B, Pop","DtMF by bad bunny, luther by kendrick and sza,...",I like the music and just seeing the general h...,I don't typically like the drinking environmen...,1,...,5,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN
5,2/25/2026 12:42:39,non-binary,"Hip Hop & R&B, Electronic, indie",2,19,"Electronic, Pop","bleed - malcolm todd, midnight sun - zara lars...",music + environment is everything! i just like...,"it can get cold if it's outside, sometimes you...",4,...,4,ambience + dancing,"to connect with people, to have fun with friends",asian,american,2,3,suree; mjsok@ucsd.edu,"talk talk - charli xcx, stateside + bladee - p...","yes; if the music is good, i tend to have a go..."
6,2/25/2026 12:45:44,woman,Hip Hop & R&B,3,20,"Hip Hop & R&B, Electronic, Pop, edm","talking body- tove lo, roses- chain smokers, b...",everyone is very friendly and only there for a...,some have too much to drink and need people to...,5,...,4,"dancing, high energy, good vibes, memorable",to socialize (ironically),vietnamese,american,2,1,no sorry😓😓,"latch- disclosure, doses&mimosas- cherub, savi...",i enjoyed witnessing everyone that was not sober
7,2/25/2026 12:47:58,woman,"Hip Hop & R&B, Indie, Alternative",4,19,"Hip Hop & R&B, Pop","The Exit Conan Gray, In My Room Julia Wolf, Le...",this is a loaded question and I've never been ...,I don't wanna get in trouble,1,...,5,having fun and excitement,I don't go to parties but someone might attend...,Filipino,American,1,1,I don't have experience,I have no idea,NaN
8,2/25/2026 13:13:12,woman,"Metal/ Rock, Jazz/ Classical, Pop, Indie",3,23,Pop,"Someone to Call My Lover by Janet Jackson, Hou...",I like that my friends are there :-) my friend...,I HATE when parties have super loud music and ...,1,...,4,It depends on the party. I don’t throw ragers ...,To spend time with friends (people I know) :-)...,Southeast Asian; Vietnamese,USA,2,1,brittneydnguyen@gmail.com,"All I Ever Asked by Rachel Chinouriri, Love is...","Yes. Honestly, I prefer to be sober at parties..."
9,2/25/2026 13:31:38,man,"Metal/ Rock, Jazz/ Classical, Pop, indie",2,21,"Metal/ Rock, Jazz/ Classical, Pop, indie",hangang by hoody,It’s fun to talk to people I know in a differe...,"Loudness, too may people, substances being use...",1,...,2,ambience,Usually out of obligation or to hang out with ...,hispanic/latino/mexican,american,1,1,santiago.valdivia1111@gmail.com,"deep in it by berlioz, breezy (inst.) by rolle...","I have only been sober at parties, and it can ..."
10,2/25/2026 13:43:47,woman,"Metal/ Rock, Electronic, Pop",3,21,"Metal/ Rock, Electronic, Pop","Everything is embarrassing, von Dutch, inténta...",The music and the open minded kind people.,If people are not inviting to everyone at the ...,4,...,5,Depends on the type of party and type of peopl...,To have fun with my friends.,Hispanic,Salvadoran and Guatemalan,2,4,No,"Tiene espinas el rosal, love generation, inolv...",I was more calm and not as willing to talk to ...
11,2/25/2026 13:57:15,woman,"Hip Hop & R&B, Jazz/ Classical, Pop",2,20,Hip Hop & R&B,"Again, my way, time of our lives, kiss me thru...",meeting new people,Most music is edm nowadays or edm remixes; not...,5,...,4,"Easy to sing along, old classics",Dress nice and have fun with friends,Vietnamese,American,1,4,No,"Gasolina, no hands, party rock anthem, clarity...",No
12,2/25/2026 13:57:57,woman,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Pop",none,environment and people,the aftermath mess,5,...,4,to get lit,"to get lit, meet new ppl, have fun",filipino,idk,4,5,NaN,i don’t host,nope
13,2/25/2026 14:38:57,woman,"Metal/ Rock, Hip Hop & R&B, Jazz/ Classical, P...",4,20,"Hip Hop & R&B, Electronic, Pop","trap queen-fetty wap, roses- chainsmokers, cla...","music, the people, meeting some new people, da...",sweatiness and pushing also chuds and creepy guys,4,...,5,"dance, singing, ambiance, nostalgia, curating ...","becuase i like the ambiance, dancing, listenin...",chinese,"taiwanese, american",2,3,yur @esk01012006@gmail.com,"trap queen-fetty wap, roses- chainsmokers, cla...","yes, it can be just as fun with the right peop..."
14,2/25/2026 15:23:33,woman,"Hip Hop & R&B, Pop",3,20,"Hip Hop & R&B, Electronic, Pop","No Hands, OMG, Blackout, Blame It, Issues","Good music, good drinks, good vibes & people",Vibes that are not welcoming,4,...,2,Depends on the vibe of the look,For fun and to socialize with new people/curre...,Vietnamese,Asian American,2,2,NaN,NaN,NaN
15,2/25/2026 16:37:26,woman,"Hip Hop & R&B, Jazz/ Classical, Pop",2,20,"Hip Hop & R&B, Jazz/ Classical, Pop","1) A Couple Minutes by Olivia Dean, 2) Who Kno...","I love the music, environment, and games",People. If I'm not surrounded by people I clic...,2,...,4,"Dancing, singing, hype, raving, vibes","To meet new people, create fun memories, and a...",vietnamese,american,2,3,Yes: t9doan@ucsd.edu,"1) Clarity by Zedd, 2) Smokin Out The Window b...",No
16,2/25/2026 21:01:04,woman,"Metal/ Rock, Hip Hop & R&B, Jazz/ Classical, Pop",3,20,"Hip Hop & R&B, Pop","Ayee ladies -Travis potter , killin you hoes ...","Music , loudness, dancing, feeling free",People who be overly drunk and weird creepy guys,4,...,3,"Dancing , singing",I go to parties because I want to have fun and...,African American and Hispanic,American,3,4,J4blanco@ucsd.edu,"F.n.f -gorilla, gas pedal - sage the Gemini , ...",Yes it out but I was a little bored when I we...
17,2/25/2026 21:25:09,man,"Metal/ Rock, Hip Hop & R&B, Electronic, Pop",3,21,"Metal/ Rock, Hip Hop & R&B, Electronic, Pop","High life by daft punk, We are the people by e...",To see everyone I know and maybe people I don’...,Sometimes it will be that person that brings e...,2,...,5,I always try to make the party feel like a bet...,Just to see my friends just to talk to them be...,Hispanic,American,4,4,No thank you,"We are the people by empire of the sun, My lov...",NaN
18,2/25/2026 21:43:37,man,"Hip Hop & R&B, Electronic, Pop",4,19,"Hip Hop & R&B, Electronic, Pop",1.- Sorry -justin bieber 2.- There’s nothing h...,Music and environment,The loudness because sometimes it is very high,4,...,3,It is varied since many times it is how the at...,"To have fun, sing, dance, meet new people",NONE,Mexican,4,2,"Yes, salmup26@gmail.com or i24221220.02@puebla...","1.- Don’t stop the party, 2.- perdóname -facto...","Yes, well, it’s exciting because I really enj..."
19,2/25/2026 22:01:25,woman,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Pop","Anything clairo, drake, Daniel Caesar,A$AP, em...",Music for sure,When people get rude and pushy,1,...,5,Dancing and singing,To destress from school,Hispanic,Mexican,1,1,No thank u!,"Any drake, A$AP, Spanish music,Rihanna",I don’t really like to drink and I would say I...
20,2/25/2026 23:11:40,woman,"Metal/ Rock, Hip Hop & R&B, Electronic, Pop",2,19,"Hip Hop & R&B, Electronic, Pop","i’ll take it -sophia steel, 27a pitfield st- b...",environment and loudness. the vibes are good a...,sometimes it gets hot and sweaty. i also don’t...,3,...,5,depends on what type of party it is but i woul...,To spend time with my friends and have some fu...,vietnamese,american,3,1,yes ivanatram33@gmail.com,"throw sum mo- swae lee, we found love- rihanna...",no
21,2/26/2026 0:28:26,woman,"Country / Folk, Pop, Regional Mexican Music",3,21,"Country / Folk, Pop, Bachata/Salsa/Regional Me...","Irreplaceable(Beyonce), Can’t Remember To Forg...","The music or setlist and the environment, so f...",I like that you can meet a variety of new peop...,2,...,5,"Dancing, singing,",To step away from my routine and to make memor...,Hispanic/Mexican,Native,5,4,NaN,"El Liston De Tu Pelo(Los Angeles Azules), 20 R...",I liked that I was able to have a good time wi...
22,2/26/2026 8:11:36,woman,"Hip Hop & R&B, Pop",3,19,"Metal/ Rock, Hip Hop & R&B, Jazz/ Classical","sticky, denial is a river, daisies, I wanna lo...","I enjoy party times with friends, music does n...",Sometimes could be botheringly loud with bad-q...,2,...,4,make the vibe more hyping,"I actually barely, I'm not very into these lou...",Asian,Chinese,2,5,no,"I don't host parties, but definitely heavy bea...",no
23,2/26/2026 12:06:51,woman,"Hip Hop & R&B, Pop, Rap",3,21,"Pop, House, EDM","1. No Hands by Waka Flocka, 2. Time of Our Liv...",I like the music selection,I don’t like how crowded they are or the odor,1,...,5,I want everyone to hear a song that they like!...,Used to be frats,Bangladeshi,American,2,5,NaN,"So Easy by Olivia Dean, NEW DROP by Don Tolive...","Yes, I liked how upbeat the music was and how ..."
24,2/26/2026 14:32:23,man,"Metal/ Rock, Hip Hop & R&B, Country / Folk, Ja...",4,20,"Hip Hop & R&B, Electronic, Pop","I love it (Charlie xcx), 22 (Taylor swift), ro...",I like the music and environment.,Creepy ppl standing the corner being judgmental.,4,...,5,I expect people to dance,To have a fun time with my friends.,Hispanic,Mexican,3,3,NaN,"Gasolina (daddy yankee), Party in the USA(Mile...",It was kinda boring when I was sober because m...
25,2/26/2026 15:57:40,woman,"Electronic, Pop, Alternative, hyperpop",3,20,Pop,"Got me started Troye Sivan , just your doll sn...","1. Music 2. Environment, I love getting ready ...",I don’t like the hook up culture of some parti...,3,...,4,"Nostalgia, feel good music, club classics",They’re fun. Great way to get together with fr...,Mexican,Mexican American,1,3,I’m ok,"Clarity zedd, meet me halfway black eyed peas,...","Yes, it was honestly just as fun. I went with ..."
26,2/27/2026 0:49:08,woman,"Hip Hop & R&B, Pop, kpop",2,19,"Pop, kpop","TiK ToK (Kesha), Tonight (pinkpantheress), No ...","the environment, i like it when parties are lo...",sometimes it can get overwhelming when there a...,5,...,4,songs that i think most people would know/can ...,i like to talk to new people without any conse...,Korean,American,1,4,no thank you!,"Club Classics (charli xcx), Stay the night (Ze...","yes, but going to a party sober makes the expe..."
27,2/27/2026 16:54:07,woman,"Hip Hop & R&B, Electronic, Pop",5,21,"Electronic, Pop","Shots -LMFAO, No hands - Waka Flocka, Time of ...",The type of music and the environment,Some people get too crazy or outright rude,4,...,3,"Ofc for the people, we all wanna get cronked","Have fun, make memories and free drinks",White,Latino,2,4,epizarroalfaro@ucsd.esu,"Clarity - Zedd, Inténtalo- 3BallMTY, Porque El...","Yes, I like being more aware but when I’m not ..."
28,2/27/2026 22:58:40,woman,"Hip Hop & R&B, Electronic, Pop",2,25,"Hip Hop & R&B, Electronic, Pop","no broke boys - disco lines & tinashe, g-rave ...","music, company, vibes","at times too loud, weird strangers sometimes",5,...,3,"upbeat, danceable music, preferably more well ...",to spend time with my friends,Asian,Vietnamese,1,3,natnatnatalie18@gmail.com,"fw me (dirty) - knock2 & rhea raj, i got a que...","yes, it was a bit scary because i am socially ..."
29,3/1/2026 12:19:36,woman,"Hip Hop & R&B, Pop",3,21,"Hip Hop & R&B, Pop",-Boys a Liar pt 2 (PinkPantheress) -Smokin out...,Music,The people are sometimes very hard to approach,4,...,3,I want them to feel pumped up and excited. Typ...,To have fun and meet people,Korean,American,1,3,YES (khyun@ucsd.edu),"-MyWay (Fetty Wap), Maneater (Nelly Furtado), ...",Yes. It was nice getting to know people and ha...

#### Nationality Clean-Up

People also appratently don't know the difference b/w nationality aand ethnicity sooo lemme clean that up

In [20]:
# lemme group by the nationality and ethnicity columns to see the unique values in each column and how many people belong to each category:
survey_df.groupby('nationality')['ethnicity'].value_counts()

nationality                ethnicity
American                   Vietnamese                        3
                           Korean                            2
                           Bangladeshi                       1
                           Filipino                          1
American                   Hispanic                          2
                           African American and Hispanic     1
                           Chinese/Vietnamese                1
Asian American             Vietnamese                        1
Chinese                    Asian                             1
Latino                     White                             1
Meixcan-American           Latino                            1
Mexican                    Hispanic                          1
                           NONE                              1
Mexican                    Hispanic                          1
Mexican American           Mexican                           1
Native                     Hispanic/Mexican                  1
Salvadoran and Guatemalan  Hispanic                          1
USA                        Southeast Asian; Vietnamese       1
Vietnamese                 Asian                             1
american                   asian                             1
                           hispanic/latino/mexican           1
                           vietnamese                        1
american                   vietnamese                        1
                           vietnamese                        1
idk                        filipino                          1
taiwanese, american        chinese                           1
Name: count, dtype: int64

Ok so now we have 3 categories for gender: 'man', 'woman', and 'non-binary' for the gender column!

## Tidying Survey Data

Now we wanna make sure our data is nice and tidy (1 observation per row, 1 variable per column, and 1 value per cell). This is gonna be tough because we have some columns that are open-ended questions, notably the "top 5" answers which include 5 songs per response (usually, there's some people who don't even write the 5 songs + artists out ToT).

sources:
- [Deepnote: Cleaning and Tidying Data with Python](https://deepnote.com/blog/cleaning-and-tidying-data-in-pandas)

In [13]:
# checking data types
survey_df.dtypes

Timestamp                                   object
gender                                      object
preferred_genre_daily                       object
introversion_score                           int64
age                                          int64
preferred_genre_parties                     object
top_5_songs_before_going_out                object
party_likes                                 object
parties_dislikes                            object
pregame_likelihood_score                     int64
times_in_last_2_months                      object
emotions_top_5_songs                        object
likelihood_approach_stranger_score           int64
likelihood_sing_along_score                  int64
party_playlist_intent                       object
reason_for_going_to_parties                 object
ethnicity                                   object
nationality                                 object
likelihood_conversation_no_music_score       int64
likelihood_conversation_loud_music_score     int64
interview_participation_email               object
top_5_songs_when_hosting_party              object
party_experience_sober                      object
dtype: object

# 2) Wrangling

# 3) EDA - what patterns do we see?