*this is where i'll work on the survey response data*

# 1) Clean & Tidy data 

This will take up the largest chunk of our time!

## Load Data & Packages

First let's load in and look at our raw data:

In [1]:
# import packages
import pandas as pd # for data manipulation
import numpy as np # for operations and uniforming data
import matplotlib.pyplot as plt # for data viz
import seaborn as sns #for data viz

# load raw data (this is a version of survey when there were 30 responses, but the column names are the same as the version with 50 responses, so we can use this for testing our code before we run it on the full dataset)

csv_file = '../data/raw/164_survey_total40.csv'
survey_raw_df = pd.read_csv(csv_file)

# view data
survey_raw_df.head()

,Timestamp,Score,First and Last Name,Email,Do you believe yourself to be Introverted or Extroverted?,What is your gender identity?,Which category best describes you? (select all that apply),What is your preferred music genre? (on a daily basis),"On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)",How old are you?,...,"When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?",Why do you go to parties?,What is/are your ethnicity/ies?,What is/are your nationality/ ies?,"On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)","On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?","Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)","Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*","Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)",Column 12
0,2/25/2026 12:10:43,NaN,NaN,NaN,NaN,Male,NaN,"Electronic, Pop",3,23,...,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i...",NaN
1,2/25/2026 12:19:46,NaN,NaN,NaN,NaN,Female,NaN,Hip Hop & R&B,2,20,...,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more",NaN
2,2/25/2026 12:21:41,NaN,NaN,NaN,NaN,Female,NaN,"Hip Hop & R&B, Pop",4,21,...,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ...",NaN
3,2/25/2026 12:32:51,NaN,NaN,NaN,NaN,female,NaN,"Hip Hop & R&B, Pop",3,19,...,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...,NaN
4,2/25/2026 12:38:44,NaN,NaN,NaN,NaN,Female,NaN,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,...,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN,NaN

There's a bunch of columns that we actually don't need because no data ended up being needed to be recorded from them so I'll get rid of those:

In [2]:
# see column names
survey_raw_df.columns

Index(['Timestamp', 'Score', 'First and Last Name ', 'Email',
       'Do you believe yourself to be Introverted or Extroverted?',
       'What is your gender identity? ',
       'Which category best describes you? (select all that apply) ',
       'What is your preferred music genre? (on a daily basis) ',
       'On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)',
       'How old are you? ', 'What is your college major? ', 'Email Address',
       'On a daily basis, what is the language of music you listen to? ',
       'What is your preferred music genre to listen to at parties? ',
       'What are your top 5 Artists for going out? ',
       'What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*',
       'What do you like about the parties you have gone to so far? (music, environment, loudness, etc. ) ',
       'What don't you like about parties? (music, environment, loudness, etc. ) ',
       'On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)',
       'How many times have you gone to a gathering in the last 2 months?',
       'What emotions do you feel when listening to these top 5 songs?',
       'On a scale of 1-5, how likely are you to come up to a stranger at a party sober? \n(1 = very unlikely, 5 = very likely)',
       'On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)',
       'When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?',
       'Why do you go to parties?', 'What is/are your ethnicity/ies?',
       'What is/are your nationality/ ies?',
       'On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)',
       'On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?',
       'Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)',
       'Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*',
       'Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)',
       'Column 12'],
      dtype='object')

In [3]:
# removing columns that are not needed for analysis which are the ones with all missing values
survey_df = survey_raw_df.dropna(axis=1, how='all')

survey_df.head()

,Timestamp,What is your gender identity?,What is your preferred music genre? (on a daily basis),"On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)",How old are you?,What is your preferred music genre to listen to at parties?,"What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*","What do you like about the parties you have gone to so far? (music, environment, loudness, etc. )","What don't you like about parties? (music, environment, loudness, etc. )","On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)",...,"On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)","When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?",Why do you go to parties?,What is/are your ethnicity/ies?,What is/are your nationality/ ies?,"On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)","On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?","Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)","Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*","Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)"
0,2/25/2026 12:10:43,Male,"Electronic, Pop",3,23,"Hip Hop & R&B, Pop","Rhianna - Where Have You Been, Bad Bunny - EoO...","I liked the music they've had, and the convers...",I don't like when others excessively use subst...,4,...,5,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i..."
1,2/25/2026 12:19:46,Female,Hip Hop & R&B,2,20,"Hip Hop & R&B, Electronic, Pop","Melancholy Hill, any Rocco song, Love Me Not, ...","The people there, the loudness","The environment, how parties always happe so late",2,...,5,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more"
2,2/25/2026 12:21:41,Female,"Hip Hop & R&B, Pop",4,21,"Hip Hop & R&B, Electronic, Pop",any spanish reggaeton song or early 2000s pop ...,"music, dancing, and environment","If the music is bad, awkward people or not eno...",5,...,3,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ..."
3,2/25/2026 12:32:51,female,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Electronic, Pop","time to pretend mgmt, spin about you drake, lo...","music, chalant people, welcoming crowd",rude nonchalant people,2,...,1,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...
4,2/25/2026 12:38:44,Female,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,"Hip Hop & R&B, Pop","DtMF by bad bunny, luther by kendrick and sza,...",I like the music and just seeing the general h...,I don't typically like the drinking environmen...,1,...,5,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN

## Renaming Columns

The column names are pretty long so I'll reformat them to be easier to call on and stuff:

In [4]:
# getting column names again after dropping columns and also seeing how many questions there are in the survey

i=0
for col in survey_df.columns:
    print(f"#{i}: {col}")
    i += 1

survey_df.columns.to_list()

#0: Timestamp
#1: What is your gender identity?
#2: What is your preferred music genre? (on a daily basis)
#3: On a scale of 1-5, how introverted are you?
(1 = introverted, 5 = extroverted)
#4: How old are you?
#5: What is your preferred music genre to listen to at parties?
#6: What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)?

*Please specify song title and artist(s)!*
#7: What do you like about the parties you have gone to so far? (music, environment, loudness, etc. )
#8: What don't you like about parties? (music, environment, loudness, etc. )
#9: On a scale of 1-5, how likely are you to pregame before a party/gathering?
(1 = very unlikely, 5 = very likely)
#10: How many times have you gone to a gathering in the last 2 months?
#11: What emotions do you feel when listening to these top 5 songs?
#12: On a scale of 1-5, how likely are you to come up to a stranger at a party sober?
(1 = very unlikely, 5 = very likely)
#13: On a scale of 1-5, how likely are you to sing along to a song at a party sober?
(1 = very unlikely, 5 = very likely)
#14: When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?
#15: Why do you go to parties?
#16: What is/are your ethnicity/ies?
#17: What is/are your nationality/ ies?
#18: On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?
(1 = very unlikely, 5 = very likely)
#19: On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?
#20: Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)
#21: Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!

*Please specify song title and artist(s)!*
#22: Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)

['Timestamp',
 'What is your gender identity? ',
 'What is your preferred music genre? (on a daily basis) ',
 'On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)',
 'How old are you? ',
 'What is your preferred music genre to listen to at parties? ',
 'What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*',
 'What do you like about the parties you have gone to so far? (music, environment, loudness, etc. ) ',
 "What don't you like about parties? (music, environment, loudness, etc. ) ",
 'On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)',
 'How many times have you gone to a gathering in the last 2 months?',
 'What emotions do you feel when listening to these top 5 songs?',
 'On a scale of 1-5, how likely are you to come up to a stranger at a party sober? \n(1 = very unlikely, 5 = very likely)',
 'On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)',
 'When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?',
 'Why do you go to parties?',
 'What is/are your ethnicity/ies?',
 'What is/are your nationality/ ies?',
 "On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)",
 "On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?",
 'Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)',
 'Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*',
 'Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)']

In [5]:
# change column names to be more descriptive and easier to work with
survey_df = survey_df.rename(columns={

    # Demographics
    'What is your gender identity? ': 'gender',
    'How old are you? ': 'age',
    'What is/are your ethnicity/ies?': 'ethnicity',
    'What is/are your nationality/ ies?': 'nationality',
    'On a scale of 1-5, how introverted are you?\n(1 = introverted, 5 = extroverted)': 'introversion_score',

    # Music Preferences
    'What is your preferred music genre? (on a daily basis) ': 'preferred_genre_daily', 
    'What is your preferred music genre to listen to at parties? ': 'preferred_genre_parties',
    'What are your top 5 songs before going out (this can be on your own or with others) (e.g., pregame, getting ready, etc.)? \n\n*Please specify song title and artist(s)!*': 'top_5_songs_before_going_out',
    'What emotions do you feel when listening to these top 5 songs?': 'emotions_top_5_songs',
    'Top 5 songs when hosting a party? If you have never hosted a party, please answer what you would put in your playlist!\n\n*Please specify song title and artist(s)!*': 'top_5_songs_when_hosting_party',    
    'When you curate your party music playlist (even hypothetically), what is your intent for the party? For the people?': 'party_playlist_intent',

    # Party Experiences
    'Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.)': 'party_experience_sober',
    'On a scale of 1-5, how likely are you to pregame before a party/gathering?\n(1 = very unlikely, 5 = very likely)': 'pregame_likelihood_score',
    'How many times have you gone to a gathering in the last 2 months?': 'times_in_last_2_months',
    'On a scale of 1-5, how likely are you to come up to a stranger at a party sober? \n(1 = very unlikely, 5 = very likely)': 'likelihood_approach_stranger_score',
    'On a scale of 1-5, how likely are you to sing along to a song at a party sober?\n(1 = very unlikely, 5 = very likely)': 'likelihood_sing_along_score',
    "On a scale of 1-5, how likely are you are you to start a conversation with someone you don't know at a party with NO music sober?\n(1 = very unlikely, 5 = very likely)": 'likelihood_conversation_no_music_score',
    "On a scale of 1-5, how likely are you to start a conversation with someone you don't know at a house party with LOUD music sober?": 'likelihood_conversation_loud_music_score',
    'Why do you go to parties?': 'reason_for_going_to_parties',
    'What do you like about the parties you have gone to so far? (music, environment, loudness, etc. ) ': 'party_likes',
    "What don't you like about parties? (music, environment, loudness, etc. ) ": 'parties_dislikes',

    # Interview Participation
    'Are you willing to participate in a short (anonymous) interview about your party experiences? (If yes, input your email)': 'interview_participation_email',
})

#let's look at the dataframe again after renaming the columns:
survey_df.head()

,Timestamp,gender,preferred_genre_daily,introversion_score,age,preferred_genre_parties,top_5_songs_before_going_out,party_likes,parties_dislikes,pregame_likelihood_score,...,likelihood_sing_along_score,party_playlist_intent,reason_for_going_to_parties,ethnicity,nationality,likelihood_conversation_no_music_score,likelihood_conversation_loud_music_score,interview_participation_email,top_5_songs_when_hosting_party,party_experience_sober
0,2/25/2026 12:10:43,Male,"Electronic, Pop",3,23,"Hip Hop & R&B, Pop","Rhianna - Where Have You Been, Bad Bunny - EoO...","I liked the music they've had, and the convers...",I don't like when others excessively use subst...,4,...,5,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i..."
1,2/25/2026 12:19:46,Female,Hip Hop & R&B,2,20,"Hip Hop & R&B, Electronic, Pop","Melancholy Hill, any Rocco song, Love Me Not, ...","The people there, the loudness","The environment, how parties always happe so late",2,...,5,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more"
2,2/25/2026 12:21:41,Female,"Hip Hop & R&B, Pop",4,21,"Hip Hop & R&B, Electronic, Pop",any spanish reggaeton song or early 2000s pop ...,"music, dancing, and environment","If the music is bad, awkward people or not eno...",5,...,3,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ..."
3,2/25/2026 12:32:51,female,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Electronic, Pop","time to pretend mgmt, spin about you drake, lo...","music, chalant people, welcoming crowd",rude nonchalant people,2,...,1,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...
4,2/25/2026 12:38:44,Female,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,"Hip Hop & R&B, Pop","DtMF by bad bunny, luther by kendrick and sza,...",I like the music and just seeing the general h...,I don't typically like the drinking environmen...,1,...,5,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN

In [6]:
# and let's look at the column names again to make sure they are correct:
survey_df.columns.to_list(), len(survey_df.columns)

(['Timestamp',
  'gender',
  'preferred_genre_daily',
  'introversion_score',
  'age',
  'preferred_genre_parties',
  'top_5_songs_before_going_out',
  'party_likes',
  'parties_dislikes',
  'pregame_likelihood_score',
  'times_in_last_2_months',
  'emotions_top_5_songs',
  'likelihood_approach_stranger_score',
  'likelihood_sing_along_score',
  'party_playlist_intent',
  'reason_for_going_to_parties',
  'ethnicity',
  'nationality',
  'likelihood_conversation_no_music_score',
  'likelihood_conversation_loud_music_score',
  'interview_participation_email',
  'top_5_songs_when_hosting_party',
  'party_experience_sober'],
 23)

So minus the timestamp, there's 22 questions total.

### Adding Participant # Column
We also don't have a participant # column, which would be nice for seeing who said what, so let's add it:

In [7]:
# adding a participant_id column to uniquely identify each participant and make it easier to work with the data:
survey_df.insert(0, 'participant_id', range(1, len(survey_df) + 1))

In [9]:
# let's look at the dataframe again after adding the participant_id column:
survey_df.tail()

,participant_id,Timestamp,gender,preferred_genre_daily,introversion_score,age,preferred_genre_parties,top_5_songs_before_going_out,party_likes,parties_dislikes,...,likelihood_sing_along_score,party_playlist_intent,reason_for_going_to_parties,ethnicity,nationality,likelihood_conversation_no_music_score,likelihood_conversation_loud_music_score,interview_participation_email,top_5_songs_when_hosting_party,party_experience_sober
35,36,3/2/2026 13:19:33,female,latin hip-hop,3,20,Hip Hop & R&B,1.) Se preparo - Ozuna 2.) Tu name - Fuerza Re...,The music and friends,How crowded they get,...,3,My intent is for everyone to let loose and get...,To have fun with my friends.,Mexican,American,1,2,bcardenasbravo@ucsd.edu,1.) Titi Me Pregunto - Bad Bunny 2.) Sabor Fre...,Yes because I was the driver of the friend gro...
36,37,3/2/2026 17:19:35,Female,"Hip Hop & R&B, Electronic, Pop",3,22,"Hip Hop & R&B, Electronic, Pop","1. COCONUT by SAILORR, 2. DOWN BAD by SAILORR,...",Mostly the people I go with and the memories w...,The feeling of needing to drink to have fun,...,4,Popular well known songs/artists and songs tha...,Friends,Asian,American,2,4,No,"1. Clarity by Zedd, 2. dashstar by knock2, 3. ...","Yes, I liked it because I get to remember ever..."
37,38,3/3/2026 0:45:15,woman,"Metal/ Rock, Electronic, Pop",3,19,"Electronic, Pop",gimme more- britney spears. maneater- nelly fu...,i like being around lots of people and talking...,"loudness, crowd crush, awkwardness when you do...",...,3,crowdpleasers everyone can yell along to,i barely do but i go to celebrate my friends a...,indian,american,3,2,no,party in the usa- miley cyrus. california gurl...,yes
38,39,3/4/2026 19:43:04,Female,"Hip Hop & R&B, Electronic, Pop",3,22,"Electronic, Pop","The Way I Are - Timbaland, Diva - Beyonce, Dis...",I've liked how everyone is down to speak to ea...,I usually don't like it if the music is too l...,...,4,I try to include crowd favourites that I know ...,"To socialise, dance, have fun, and relax.",Kazakh,Kazakh,3,4,NaN,"NOKIA - Drake, Five More Hours - Deorro, Beaut...",Yes I have. I thought it was fun
39,40,3/4/2026 22:20:37,Woman,"Hip Hop & R&B, Jazz/ Classical,",3,21,"Hip Hop & R&B, Jazz/ Classical","Ah We Ah-Ahmed Mounib, After The Beep- Faye Wo...",An excuse to dance,If the music is too loud or if you can’t dance...,...,5,To dance and feel groovy,To dance,Kurdish,American,5,2,Yes- derinm13@icloud.com,"Snap My Finger -Kaytranada ft. Pink Panthress,...","Yes, I party/dance hard"

In [10]:
# save the cleaned data to a new csv file in the interim data folder:
survey_df.to_csv('../data/interim/survey_cleaned_labels.csv', index=False)

## Brief Section Summary:

**So far, we've...**
- loaded in the original raw data
- gotten rid of columns will all-missing values (they were from a prototype version of the survey)
- renamed columns to shorter labels to call them and see them easier
- added a `participant_id` column
- saved this new version of the raw data to an interim version called `survey_cleaned_labels.csv`

*Now* we'll begin **cleaning** this interim data.

## Cleaning Survey Data

Now we wanna make sure our data is pretty clean, meaning there's no substantial amounts of missing values and see if responses are what they should be. To be honest, there shouldn't be many missing values since most questions are required (other than "Have you ever gone to a party sober? (if yes, explain your experience with it: what you liked what surprised you vs. going to a party not sober, etc.) and something else I think?)

So let's load in our new interim data and assign it to datafram called `survey_clean_df`, where we'll save a clean version of the data later:

In [12]:
interim_csv_file = '../data/interim/survey_cleaned_labels.csv'
survey_clean_df = pd.read_csv(interim_csv_file)
survey_clean_df.head()

,participant_id,Timestamp,gender,preferred_genre_daily,introversion_score,age,preferred_genre_parties,top_5_songs_before_going_out,party_likes,parties_dislikes,...,likelihood_sing_along_score,party_playlist_intent,reason_for_going_to_parties,ethnicity,nationality,likelihood_conversation_no_music_score,likelihood_conversation_loud_music_score,interview_participation_email,top_5_songs_when_hosting_party,party_experience_sober
0,1,2/25/2026 12:10:43,Male,"Electronic, Pop",3,23,"Hip Hop & R&B, Pop","Rhianna - Where Have You Been, Bad Bunny - EoO...","I liked the music they've had, and the convers...",I don't like when others excessively use subst...,...,5,"singing, ambience with good vibes",To socialize with my friends and dance.,Latino,Meixcan-American,2,3,admontan@ucsd.edu,"Bad Bunny - Baile Inolvidable, Karol G - Si An...","Yes I have. While I feel more shy sometimes, i..."
1,2,2/25/2026 12:19:46,Female,Hip Hop & R&B,2,20,"Hip Hop & R&B, Electronic, Pop","Melancholy Hill, any Rocco song, Love Me Not, ...","The people there, the loudness","The environment, how parties always happe so late",...,5,Something to pump up or fill in the lack of en...,For free drinks foods or with my friends or to...,Vietnamese,American,1,3,No,"Any Daniel ceasar song, Melancholy Hill, Every...","Yes, I laughed more"
2,3,2/25/2026 12:21:41,Female,"Hip Hop & R&B, Pop",4,21,"Hip Hop & R&B, Electronic, Pop",any spanish reggaeton song or early 2000s pop ...,"music, dancing, and environment","If the music is bad, awkward people or not eno...",...,3,dancing and ambience,"FOMO, friends are going and to take a break fr...",Hispanic,American,2,3,N/a,never hosted before but would put Spanish regg...,"Yes, I tried drinking but I ended up throwing ..."
3,4,2/25/2026 12:32:51,female,"Hip Hop & R&B, Pop",3,19,"Hip Hop & R&B, Electronic, Pop","time to pretend mgmt, spin about you drake, lo...","music, chalant people, welcoming crowd",rude nonchalant people,...,1,reminiscing & singing,make memories & to have fun,Chinese/Vietnamese,American,4,2,no,"lady killers, 3 strikes, girlfriend heavy weig...",yes it was chill everybody was already in a ha...
4,5,2/25/2026 12:38:44,Female,"Metal/ Rock, Hip Hop & R&B, Pop",2,19,"Hip Hop & R&B, Pop","DtMF by bad bunny, luther by kendrick and sza,...",I like the music and just seeing the general h...,I don't typically like the drinking environmen...,...,5,"I think having a playlist that is fun, nostalg...",Just to be with friends who are there and for ...,Vietnamese,American,3,2,No thank you,"I like all the stars by kendrick and sza, titi...",NaN

In [13]:
# checking missing values in each column
survey_clean_df.isnull().sum()

participant_id                              0
Timestamp                                   0
gender                                      0
preferred_genre_daily                       0
introversion_score                          0
age                                         0
preferred_genre_parties                     0
top_5_songs_before_going_out                0
party_likes                                 0
parties_dislikes                            0
pregame_likelihood_score                    0
times_in_last_2_months                      0
emotions_top_5_songs                        0
likelihood_approach_stranger_score          0
likelihood_sing_along_score                 0
party_playlist_intent                       0
reason_for_going_to_parties                 0
ethnicity                                   1
nationality                                 1
likelihood_conversation_no_music_score      0
likelihood_conversation_loud_music_score    0
interview_participation_email               7
top_5_songs_when_hosting_party              1
party_experience_sober                      4
dtype: int64

Interview participation email has 7 missing values and party_experience_sober also hs 4 missing values, but those are optional, so it makes sense.

But why would top_5_songs_when_hosting_party, ethnicity,*and* nationality have 1 missing  value each? Those shouldn't be optional. Let's take a look:

In [17]:
# let's look at the missing values in top_5_songs_when_hosting_party, ethnicity, and nationality columns to see if there are any patterns in the missing data:

#idk how to do this yet, but I will figure it out and add it here!

In [ ]:
# weird, row 14 yas NaN for the 3 rows, let's look at the original dataframe to see if there is something wrong with the data in that row:
survey_df.iloc[14]

honeslty idk why or how those values are missing for that individual, especially since `top_5_songs_when_hosting_party` is a required response field but maybe the survey had changed somehow since she took it? Anyway I think the mising values we have aren't a big deal so I'll go ahead and keep it as is. now we wanna tidy up the data!

### Cleaning responses & Uniforming Data

#### Gender Clean-up
Ok so clearly people don't know what nationality vs ethnicity is so we're gonna have to clean that up a bit or change it to race I honestly don't know lol.

Also for the `gender` data, people also clearly don't know the difference b/w sex and gender lol. Most ppl wrote 'female' or 'male' so maybe we can clean it up by just standardizing the responses to sex? but there were some entries like 'gender fluid (fem) and for some reason 'Straight' bruhhh'

In [ ]:
# first will make gender column uniform by changing all values to lowercase and removing extra spaces
survey_df['gender'] = survey_df['gender'].str.lower().str.strip()

# now let's see what unique values there are in the gender column to see if there are any other variations of the same gender:
survey_df['gender'].unique()

**1) 'male' / 'man'**

Ok so for males, there is 'male' & 'men' still. We could either standardize to make anything listed as that as either 'male' or 'men' --> the correct response for gender would be 'men'

**2) 'female'/ 'woman'**

For 'female' there's a lot of unqiue entries essentially saying the same thing, including 'heterosexual female', 'she/her female', and 'she/her'

**3) 'non-binary'**

There's only one response that could fit this called 'genderfluid (fem)'

*So now let's just write some code to standardize the data to gender:*

In [ ]:
# we're going to standardize the gender column by replacing all variations of the same categories ('woman', 'man', 'genderfluid') to the same value, and then we will reassign them to the gender column:
for gender in survey_df['gender']:
    if 'woman' in gender or 'she/her' in gender or 'female' in gender:
        survey_df['gender'] = survey_df['gender'].replace(gender, 'woman')
    elif 'man' in gender or 'men' in gender or 'male' in gender or 'he/him' in gender:
        survey_df['gender'] = survey_df['gender'].replace(gender, 'man')
    elif 'genderfluid' in gender or 'non-binary' in gender or 'they/them' in gender:
        survey_df['gender'] = survey_df['gender'].replace(gender, 'non-binary')

# let's check the unique values again to make sure they are standardized:
survey_df

#### Nationality Clean-Up

People also appratently don't know the difference b/w nationality aand ethnicity sooo lemme clean that up

In [ ]:
# lemme group by the nationality and ethnicity columns to see the unique values in each column and how many people belong to each category:
survey_df.groupby('nationality')['ethnicity'].value_counts()

Ok so now we have 3 categories for gender: 'man', 'woman', and 'non-binary' for the gender column!

## Tidying Survey Data

Now we wanna make sure our data is nice and tidy (1 observation per row, 1 variable per column, and 1 value per cell). This is gonna be tough because we have some columns that are open-ended questions, notably the "top 5" answers which include 5 songs per response (usually, there's some people who don't even write the 5 songs + artists out ToT).

sources:
- [Deepnote: Cleaning and Tidying Data with Python](https://deepnote.com/blog/cleaning-and-tidying-data-in-pandas)

In [ ]:
# checking data types
survey_df.dtypes

# 2) Wrangling

# 3) EDA - what patterns do we see?